// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PCPartPicker.Infrastructure.Data;

#nullable disable

namespace PCPartPicker.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("PCPartPicker.Domain.Entities.Build", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("CPUId")
                        .HasColumnType("int");

                    b.Property<int?>("CaseFanId")
                        .HasColumnType("int");

                    b.Property<int?>("CaseId")
                        .HasColumnType("int");

                    b.Property<int?>("CoolerId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime");

                    b.Property<string>("Description")
                        .HasColumnType("longtext");

                    b.Property<int?>("GPUId")
                        .HasColumnType("int");

                    b.Property<int?>("MotherboardId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int?>("PSUId")
                        .HasColumnType("int");

                    b.Property<int?>("RAMId")
                        .HasColumnType("int");

                    b.Property<string>("ShareCode")
                        .IsRequired()
                        .HasColumnType("varchar(95)");

                    b.Property<int?>("StorageId")
                        .HasColumnType("int");

                    b.Property<decimal>("TotalPrice")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("TotalWattage")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime");

                    b.HasKey("Id");

                    b.HasIndex("CPUId");

                    b.HasIndex("CaseFanId");

                    b.HasIndex("CaseId");

                    b.HasIndex("CoolerId");

                    b.HasIndex("GPUId");

                    b.HasIndex("MotherboardId");

                    b.HasIndex("PSUId");

                    b.HasIndex("RAMId");

                    b.HasIndex("ShareCode")
                        .IsUnique();

                    b.HasIndex("StorageId");

                    b.ToTable("Builds");
                });

            modelBuilder.Entity("PCPartPicker.Domain.Entities.Part", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Category")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("varchar(13)");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("longtext");

                    b.Property<string>("Manufacturer")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<decimal>("Price")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("ProductUrl")
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime");

                    b.Property<int?>("Wattage")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Part");

                    b.HasDiscriminator().HasValue("Part");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("PCPartPicker.Domain.Entities.CPU", b =>
                {
                    b.HasBaseType("PCPartPicker.Domain.Entities.Part");

                    b.Property<decimal>("BaseClock")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)");

                    b.Property<decimal>("BoostClock")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)");

                    b.Property<int>("CoreCount")
                        .HasColumnType("int");

                    b.Property<bool>("IntegratedGraphics")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("Socket")
                        .HasColumnType("int");

                    b.Property<int>("ThreadCount")
                        .HasColumnType("int");

                    b.ToTable("Part", t =>
                        {
                            t.Property("BoostClock")
                                .HasColumnName("CPU_BoostClock");

                            t.Property("Socket")
                                .HasColumnName("CPU_Socket");
                        });

                    b.HasDiscriminator().HasValue("CPU");
                });

            modelBuilder.Entity("PCPartPicker.Domain.Entities.Case", b =>
                {
                    b.HasBaseType("PCPartPicker.Domain.Entities.Part");

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("FormFactor")
                        .HasColumnType("int");

                    b.Property<bool>("HasSidePanel")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("MaxGPULength")
                        .HasColumnType("int");

                    b.ToTable("Part", t =>
                        {
                            t.Property("FormFactor")
                                .HasColumnName("Case_FormFactor");
                        });

                    b.HasDiscriminator().HasValue("Case");
                });

            modelBuilder.Entity("PCPartPicker.Domain.Entities.CaseFan", b =>
                {
                    b.HasBaseType("PCPartPicker.Domain.Entities.Part");

                    b.HasDiscriminator().HasValue("CaseFan");
                });

            modelBuilder.Entity("PCPartPicker.Domain.Entities.Cooler", b =>
                {
                    b.HasBaseType("PCPartPicker.Domain.Entities.Part");

                    b.Property<string>("CoolerType")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("HeightMM")
                        .HasColumnType("int");

                    b.Property<int?>("RadiatorSizeMM")
                        .HasColumnType("int");

                    b.Property<int>("Socket")
                        .HasColumnType("int");

                    b.ToTable("Part", t =>
                        {
                            t.Property("Socket")
                                .HasColumnName("Cooler_Socket");
                        });

                    b.HasDiscriminator().HasValue("Cooler");
                });

            modelBuilder.Entity("PCPartPicker.Domain.Entities.GPU", b =>
                {
                    b.HasBaseType("PCPartPicker.Domain.Entities.Part");

                    b.Property<int>("BoostClock")
                        .HasColumnType("int");

                    b.Property<string>("Chipset")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("CoreClock")
                        .HasColumnType("int");

                    b.Property<int>("Length")
                        .HasColumnType("int");

                    b.Property<int>("MemoryGB")
                        .HasColumnType("int");

                    b.Property<string>("MemoryType")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("Slots")
                        .HasColumnType("int");

                    b.ToTable("Part", t =>
                        {
                            t.Property("Chipset")
                                .HasColumnName("GPU_Chipset");

                            t.Property("MemoryType")
                                .HasColumnName("GPU_MemoryType");
                        });

                    b.HasDiscriminator().HasValue("GPU");
                });

            modelBuilder.Entity("PCPartPicker.Domain.Entities.Motherboard", b =>
                {
                    b.HasBaseType("PCPartPicker.Domain.Entities.Part");

                    b.Property<string>("Chipset")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("FormFactor")
                        .HasColumnType("int");

                    b.Property<int>("M2Slots")
                        .HasColumnType("int");

                    b.Property<int>("MaxMemoryGB")
                        .HasColumnType("int");

                    b.Property<int>("MemorySlots")
                        .HasColumnType("int");

                    b.Property<int>("MemoryType")
                        .HasColumnType("int");

                    b.Property<int>("PCIeSlots")
                        .HasColumnType("int");

                    b.Property<int>("SataSlots")
                        .HasColumnType("int");

                    b.Property<int>("Socket")
                        .HasColumnType("int");

                    b.ToTable("Part", t =>
                        {
                            t.Property("FormFactor")
                                .HasColumnName("Motherboard_FormFactor");
                        });

                    b.HasDiscriminator().HasValue("Motherboard");
                });

            modelBuilder.Entity("PCPartPicker.Domain.Entities.PSU", b =>
                {
                    b.HasBaseType("PCPartPicker.Domain.Entities.Part");

                    b.Property<string>("Efficiency")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("FormFactor")
                        .HasColumnType("int");

                    b.Property<bool>("Modular")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("WattageRating")
                        .HasColumnType("int");

                    b.HasDiscriminator().HasValue("PSU");
                });

            modelBuilder.Entity("PCPartPicker.Domain.Entities.RAM", b =>
                {
                    b.HasBaseType("PCPartPicker.Domain.Entities.Part");

                    b.Property<int>("CASLatency")
                        .HasColumnType("int");

                    b.Property<int>("CapacityGB")
                        .HasColumnType("int");

                    b.Property<int>("ModuleCount")
                        .HasColumnType("int");

                    b.Property<int>("SpeedMHz")
                        .HasColumnType("int");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.HasDiscriminator().HasValue("RAM");
                });

            modelBuilder.Entity("PCPartPicker.Domain.Entities.Storage", b =>
                {
                    b.HasBaseType("PCPartPicker.Domain.Entities.Part");

                    b.Property<int>("CapacityGB")
                        .HasColumnType("int");

                    b.Property<string>("Interface")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int?>("ReadSpeedMBps")
                        .HasColumnType("int");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int?>("WriteSpeedMBps")
                        .HasColumnType("int");

                    b.ToTable("Part", t =>
                        {
                            t.Property("CapacityGB")
                                .HasColumnName("Storage_CapacityGB");

                            t.Property("Type")
                                .HasColumnName("Storage_Type");
                        });

                    b.HasDiscriminator().HasValue("Storage");
                });

            modelBuilder.Entity("PCPartPicker.Domain.Entities.Build", b =>
                {
                    b.HasOne("PCPartPicker.Domain.Entities.CPU", "CPU")
                        .WithMany()
                        .HasForeignKey("CPUId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("PCPartPicker.Domain.Entities.CaseFan", "CaseFan")
                        .WithMany()
                        .HasForeignKey("CaseFanId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("PCPartPicker.Domain.Entities.Case", "Case")
                        .WithMany()
                        .HasForeignKey("CaseId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("PCPartPicker.Domain.Entities.Cooler", "Cooler")
                        .WithMany()
                        .HasForeignKey("CoolerId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("PCPartPicker.Domain.Entities.GPU", "GPU")
                        .WithMany()
                        .HasForeignKey("GPUId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("PCPartPicker.Domain.Entities.Motherboard", "Motherboard")
                        .WithMany()
                        .HasForeignKey("MotherboardId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("PCPartPicker.Domain.Entities.PSU", "PSU")
                        .WithMany()
                        .HasForeignKey("PSUId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("PCPartPicker.Domain.Entities.RAM", "RAM")
                        .WithMany()
                        .HasForeignKey("RAMId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("PCPartPicker.Domain.Entities.Storage", "Storage")
                        .WithMany()
                        .HasForeignKey("StorageId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("CPU");

                    b.Navigation("Case");

                    b.Navigation("CaseFan");

                    b.Navigation("Cooler");

                    b.Navigation("GPU");

                    b.Navigation("Motherboard");

                    b.Navigation("PSU");

                    b.Navigation("RAM");

                    b.Navigation("Storage");
                });
#pragma warning restore 612, 618
        }
    }
}
